loopback_users.guest = false

federation.upstream.eu.uri   = amqp://guest:guest@10.0.1.11
federation.upstream.us.uri   = amqp://guest:guest@10.0.2.11
federation.upstream.apac.uri = amqp://guest:guest@10.0.3.11
